### ISSUE TITLE
Question about the resample function

### ISSUE THREAD

**Issue by tel** [blei-lab/variational-smc#1]
Hi, 

I've been trying to read through this reference implementation to better understand how to implement VSMC. I think I've got most things figured out, but I don't understand the resample function for two reasons:

1. Why are you ignoring the gradient w.r.t. to it?
2. What kind of sampling are you doing there? You call it stratified resampling, but that doesn't seem to be mentioned in the paper.

In the paper, the resampling step seems to be accomplished using a normal categorical draw. Is that function somehow simulating it? If so, I'm not entirely sure how, since it seems to disperse the `u` parameter somewhat uniformly across [0, 1]. At that rate, larger weights can pick up more resamples, but there's a limit. As I see it, a weight has to be at least as large as (n-1)/N in order to have positive probability of being resampled n times.

Maybe I'm misunderstanding the function or the paper, but I'm very curious what the proper way to implement sampling should be.

Thanks,
Joseph

**Comment by naesseth** [comment]
Hi Joseph,

1. The reason for ignoring the gradient is explained and illustrated in the paper, see the paragraph on Stochastic Optimization in the methods section (section 3). Essentially it is because the variance is very high and including it did not lead to much improvement in simulated data experiments (first example in the experiments section).

2. Yes, not mentioning stratified resampling in the main paper was an oversight. It is a standard variance reduction technique in the resampling step often used in practice, see e.g. my tutorial on SMC, "Elements of Sequential Monte Carlo" for a thorough discussion on these. The proofs and algorithm are derived for what is known as multinomial resampling, in which you would replace the stratification by simply sampling all N uniformly and independently u ~ U(0,1). This is would correspond to the categorical distribution. The algorithm will still be correct when using stratified resampling, the proofs just become a bit more involved. The main difference you would see when comparing the two in practice is that stratified resampling tends to lower the variance of your estimate slightly without impacting the theoretical properties of the SMC algorithm.

Best,
Christian

**Comment by tel** [comment]
Hi Christian,

Your response is very helpful! I suspected the latter, but didn't immediately know how to connect the components. I'll review your tutorial next, thanks for the pointer.

I'm pretty amazed by (1), though. I had wondered if that was the reason, but it's kind of amazing to me that the whole term is elided so simply. I'm still pretty new to modern AD tools, so being able to eliminate that term so easily is unexpected, and nice!

Thanks for your fast reply!
Joseph
